vim.opt.ambiwidth = "double"
vim.opt.autoindent = true
vim.opt.backup = false
vim.opt.clipboard = "unnamed,unnamedplus"
vim.opt.cursorline = true
vim.opt.encoding = "utf-8"
vim.opt.fileencodings = "ucs-bom,utf-8,iso-2022-jp,cp932,euc-jp,default,latin"
vim.opt.hidden = true
vim.opt.hlsearch = true
vim.opt.ignorecase = true
vim.opt.incsearch = true
vim.opt.infercase = true
vim.opt.list = true
vim.opt.listchars = "tab:>-,trail:-,eol:$,extends:>,precedes:<,nbsp:%"
vim.opt.modeline = true
vim.opt.number = true
vim.opt.shiftround = true
vim.opt.showmatch = true
vim.opt.smartcase = true
vim.opt.smartindent = true
vim.opt.smarttab = true
vim.opt.spell = false
vim.opt.swapfile = false
vim.opt.switchbuf = "useopen"
vim.opt.termguicolors = true
vim.opt.termguicolors = true
vim.opt.textwidth = 0
vim.opt.visualbell = false
vim.opt.wrap = true
vim.opt.writebackup = false

-- feature-specific options
vim.lsp.set_log_level("off")
