[[plugins]]
repo = 'neoclide/coc-git'

[[plugins]]
repo = 'neoclide/coc-json'

[[plugins]]
repo = 'neoclide/coc-python'

[[plugins]]
repo = 'neoclide/coc-yank'

[[plugins]]
repo = 'neoclide/coc-yaml'

[[plugins]]
repo = 'yuki-ycino/fzf-preview.vim'

[[plugins]]
repo = 'josa42/coc-sh'

[[plugins]]
repo = 'oncomouse/coc-fish'

[[plugins]]
repo = 'pappasam/coc-jedi'

[[plugins]]
repo = 'fannheyward/coc-markdownlint'

[[plugins]]
repo = 'iamcco/coc-diagnostic'
