[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'Townk/vim-autoclose'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'godlygeek/tabular'

[[plugins]]
repo = 'plasticboy/vim-markdown'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'davidhalter/jedi-vim'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'kana/vim-submode'
