[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'Townk/vim-autoclose'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'godlygeek/tabular'

[[plugins]]
repo = 'plasticboy/vim-markdown'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'zchee/deoplete-jedi'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'kana/vim-submode'

[[plugins]]
repo = 'millermedeiros/vim-statline'

[[plugins]]
repo = 'tpope/vim-pathogen'

[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'python-mode/python-mode'

[[plugins]]
repo = 'powerman/vim-plugin-viewdoc'

[[plugins]]
repo = 'tmux-plugins/vim-tmux'

[[plugins]]
repo = 'tmux-plugins/vim-tmux-focus-events'

[[plugins]]
repo = 'dag/vim-fish'

[[plugins]]
repo = 'kassio/neoterm'

[[plugins]]
repo = 'AndrewRadev/switch.vim'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'Shougo/vimproc.vim'

[[plugins]]
repo = 'junegunn/fzf.vim'
