#!/bin/bash

if [ $# -eq 2 ]; then
	if [ "$1" = "alnum" ] || [ "$1" = "print" ] || [ "$1" = "digit" ]; then
		TYPE=$1
	else
		echo "Invalid argument: '$1'"
		exit 22
	fi
	LENGTH=$2
else
	cat <<- EOT > /dev/stderr
	Usage: $0 <alnum|print|digit> LENGTH

	Generate random string with LENGTH length

	Options:
	    alnum    Generate string only with alphabets and numbers
	    print    Generate string with ASCII letters
	    digit    Generate string only with numeric letters
	EOT
	exit 22
fi

LC_ALL=C tr -dc '[:'"${TYPE}"':]' < /dev/random | head -c "${LENGTH}"
