#!/bin/fish

function report
	echo -e "\033[1;37m$argv\033[0;39m"
end

function load_ssh_keys
	set BASEDIR "$HOME/.ssh"
	for SUBDIR in (ls -l $BASEDIR | grep '^d' | awk '{print $8}' | sed -e 's/\///g')
		set SSH_DIR "$BASEDIR/$SUBDIR"
		report "Load SSH keys in $SSH_DIR"
		for KEY in (ls $SSH_DIR | grep id_ | grep -v '.pub')
			set SSH_KEY "$SSH_DIR/$KEY"
			get --prompt "Load '$SSH_KEY' ? [y/N]" | read -l CONFIRM
			switch $CONFIRM
				case Y y
					ssh-add "$SSH_KEY"
			end
		end
	end
end

function update_fisherman_plugins
	report "Update fisherman plugins"
	fisher update
end

function update_pkgs_in_venvs
	set BASEDIR "$HOME/Venvs"
	for SUBDIR in (ls -l $BASEDIR | grep '^d' | awk '{print $8}' | sed -e 's/\///g')
		set VENV_DIR "$BASEDIR/$SUBDIR"
		set ACTIVATE "source $VENV_DIR/bin/activate"
		report "Update packages in venv $VENV_DIR"
		set PIP_PKGS (bash -c "$ACTIVATE; pip list --format=freeze | awk -F= '{print $1}'")
		bash -c "$ACTIVATE; pip install --upgrade $PIP_PKGS"
	end
end

report "Hello!"
load_ssh_keys
update_fisherman_plugins
update_pkgs_in_venvs
report "Done! Have a nice day!"
