#!/bin/fish

function load_ssh_keys
	set SSH_DIR "$HOME/.ssh"
	echo "Load SSH keys in $HOME/.ssh/"
	for KEY in (ls $SSH_DIR | grep id_ | grep -v '.pub')
		set SSH_KEY "$SSH_DIR/$KEY"
		get --prompt "Load '$SSH_KEY' ? [y/N]" | read -l CONFIRM
		switch $CONFIRM
			case Y y
				ssh-add "$SSH_KEY"
		end
	end
end

function update_fisherman_plugins
	echo "Update fisherman plugins."
	fisher update
end

echo "Hello!"
load_ssh_keys
update_fisherman_plugins
echo "Done! Have a nice day!"
